name: "Install Graphviz"
description: "Installs Graphviz (dot command) on Ubuntu, Windows, or macOS runners"
runs:
  using: "composite"
  steps:
    - name: Install Graphviz on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Install Graphviz on Windows
      if: runner.os == 'Windows'
      run: |
        choco install graphviz -y

    - name: Install Graphviz on macOS
      if: runner.os == 'macOS'
      run: |
        brew install graphviz