on:
  workflow_call:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: 'e-CODEX/workflows'
          path: 'workflows'
          ref: 'main'

      - uses: dbelyaev/action-checkstyle@ada3d54c61a086e8d8348886a212c4a2a9411e3c # v1.17.2
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: workflows/checkstyle.xml
