name: "Publish Release to Maven Repository"
on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to use for the build."
        required: true
        type: number
        default: 21
      maven-parameters:
        description: "Extra parameters to pass to Maven"
        required: false
        type: string
        default: ""
      maven-repo-id:
        description: "Maven repository ID"
        required: true
        type: string
      tag:
        description: 'The tag to checkout (optional)'
        required: false
        type: string
      environment:
        description: "Deployment environment"
        required: false
        type: string
        default: "production"

permissions:
  contents: read

jobs:        
  publish-release:
    name: Publish Release to Maven Repository
    permissions:
      contents: write
      attestations: write # Required for attestation
      id-token: write # Required for JFrog CLI setup
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - name: Checkout repository
        if: ${{ !inputs.tag }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Graphviz
        uses: e-CODEX/workflows/.github/actions/install-graphviz@main
        
      - name: Checkout tag
        if: ${{ inputs.tag }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@f748a0599171a192a2668afee8d0497f7c1069df # v4.5.6
        id: setup-jfrog-cli
        env:
            JF_URL: https://scm.ecodex.eu
        with:
            oidc-provider-name: setup-jfrog   

      - uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b # v3.1.0
        with:
          servers: |
            [{
              "id": "${{ inputs.maven-repo-id }}",
              "username": "${{ steps.setup-jfrog-cli.outputs.oidc-user }}",
              "password": "${{ steps.setup-jfrog-cli.outputs.oidc-token }}"
            }]

      - name: Submit Dependency Release to GitHub Advanced Security
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5.0.0

      - name: Publish Release
        run: mvn -B -e deploy -DrepositoryId=${{ inputs.maven-repo-id }} ${{ inputs.maven-parameters }}
